# Generated by Django 5.0.4 on 2024-04-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='articledb',
            name='Auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author'),
        ),
    ]
